{% set name = "polar2grid" %}
{% set version = "3.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polar2grid-{{ version }}.tar.gz
  sha256: 4b1b177d5cdcada04bd63a572361bb13580d544c13e8fe7864d491022253a698

build:
  number: 0
  noarch: python
  entry_points:
    - polar2grid=polar2grid.__main__:p2g_main
    - geo2grid=polar2grid.__main__:g2g_main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - h5py
    - netcdf4
    - python >=3.8
    - rasterio
    - satpy
    - setuptools

test:
  imports:
    - polar2grid
    - polar2grid.glue
  commands:
    - pip check
    - polar2grid --help
    - geo2grid --help
  requires:
    - pip

about:
  home: http://www.ssec.wisc.edu/software/polar2grid/
  summary: Library and scripts to remap satellite data to a grid
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - djhoese
