{% set name = "polar2grid" %}
{% set version = "3.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/polar2grid-{{ version }}.tar.gz
  sha256: 2f9c721f0756550b6b507a792ee0da4ac781df0dbbc5d0a8d3c1db7c006f5b71

build:
  number: 0
  noarch: python
  entry_points:
    - polar2grid=polar2grid.__main__:p2g_main
    - geo2grid=polar2grid.__main__:g2g_main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools
  run:
    - h5py
    - netcdf4
    - python >=3.10
    - rasterio
    - satpy
    - setuptools

test:
  imports:
    - polar2grid
    - polar2grid.glue
  commands:
    - pip check
    - polar2grid --help
    - geo2grid --help
  requires:
    - pip

about:
  home: http://www.ssec.wisc.edu/software/polar2grid/
  summary: Library and scripts to remap satellite data to a grid
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - djhoese
